<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="urllib.error --- 由 urllib.request 引发的异常类" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://docs.python.org/3/library/urllib.error.xhtml" />
<meta property="og:site_name" content="Python documentation" />
<meta property="og:description" content="源代码： Lib/urllib/error.py[https://github.com/python/cpython/tree/3.12/Lib/urllib/error.py] urllib.error 模块为 urllib.request 所引发的异常定义了异常类。 基础异常类是 URLError 。 下列异常会被 urllib.error 按需引发：" />
<meta property="og:image" content="https://docs.python.org/3/_static/og-image.png" />
<meta property="og:image:alt" content="Python documentation" />
<meta name="description" content="源代码： Lib/urllib/error.py[https://github.com/python/cpython/tree/3.12/Lib/urllib/error.py] urllib.error 模块为 urllib.request 所引发的异常定义了异常类。 基础异常类是 URLError 。 下列异常会被 urllib.error 按需引发：" />
<meta property="og:image:width" content="200" />
<meta property="og:image:height" content="200" />
<meta name="theme-color" content="#3776ab" />

    <title>urllib.error --- 由 urllib.request 引发的异常类</title>
    <link rel="stylesheet" type="text/css" href="../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../_static/epub.css" />
    <link rel="canonical" href="https://docs.python.org/3/library/urllib.error.html" />
    
      
    

    
    <style>
      @media only screen {
        table.full-width-table {
            width: 100%;
        }
      }
    </style>
 

  </head><body>


    <div class="document">
      <div class="documentwrapper">
          <div class="body" role="main">
            
  <section id="module-urllib.error">
<span id="urllib-error-exception-classes-raised-by-urllib-request"></span><h1><code class="xref py py-mod docutils literal notranslate"><span class="pre">urllib.error</span></code> --- 由 urllib.request 引发的异常类</h1>
<p><strong>源代码：</strong> <a class="reference external" href="https://github.com/python/cpython/tree/3.12/Lib/urllib/error.py">Lib/urllib/error.py</a><span class="link-target"> [https://github.com/python/cpython/tree/3.12/Lib/urllib/error.py]</span></p>
<hr class="docutils" />
<p><a class="reference internal" href="#module-urllib.error" title="urllib.error: Exception classes raised by urllib.request."><code class="xref py py-mod docutils literal notranslate"><span class="pre">urllib.error</span></code></a> 模块为 <a class="reference internal" href="urllib.request.xhtml#module-urllib.request" title="urllib.request: Extensible library for opening URLs."><code class="xref py py-mod docutils literal notranslate"><span class="pre">urllib.request</span></code></a> 所引发的异常定义了异常类。 基础异常类是 <a class="reference internal" href="#urllib.error.URLError" title="urllib.error.URLError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">URLError</span></code></a>。</p>
<p>下列异常会被 <a class="reference internal" href="#module-urllib.error" title="urllib.error: Exception classes raised by urllib.request."><code class="xref py py-mod docutils literal notranslate"><span class="pre">urllib.error</span></code></a> 按需引发：</p>
<dl class="py exception">
<dt class="sig sig-object py" id="urllib.error.URLError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">urllib.error.</span></span><span class="sig-name descname"><span class="pre">URLError</span></span></dt>
<dd><p>处理程序在遇到问题时会引发此异常（或其派生的异常）。 它是 <a class="reference internal" href="exceptions.xhtml#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a> 的一个子类。</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="urllib.error.URLError.reason">
<span class="sig-name descname"><span class="pre">reason</span></span></dt>
<dd><p>此错误的原因。 它可以是一个消息字符串或另一个异常实例。</p>
</dd></dl>

<div class="versionchanged">
<p><span class="versionmodified changed">在 3.3 版本发生变更: </span><a class="reference internal" href="#urllib.error.URLError" title="urllib.error.URLError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">URLError</span></code></a> 曾经是 <a class="reference internal" href="exceptions.xhtml#IOError" title="IOError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">IOError</span></code></a> 的子类型，现在它是 <a class="reference internal" href="exceptions.xhtml#OSError" title="OSError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">OSError</span></code></a> 的一个别名。</p>
</div>
</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="urllib.error.HTTPError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">urllib.error.</span></span><span class="sig-name descname"><span class="pre">HTTPError</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">url</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">code</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">msg</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">hdrs</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">fp</span></span></em><span class="sig-paren">)</span></dt>
<dd><p>虽然是一个异常（<a class="reference internal" href="#urllib.error.URLError" title="urllib.error.URLError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">URLError</span></code></a> 的一个子类），<a class="reference internal" href="#urllib.error.HTTPError" title="urllib.error.HTTPError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">HTTPError</span></code></a> 也可以作为一个非异常的文件类返回值（与 <a class="reference internal" href="urllib.request.xhtml#urllib.request.urlopen" title="urllib.request.urlopen"><code class="xref py py-func docutils literal notranslate"><span class="pre">urlopen()</span></code></a> 返所回的对象相同）。 这适用于处理特殊 HTTP 错误例如作为认证请求的时候。</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="urllib.error.HTTPError.url">
<span class="sig-name descname"><span class="pre">url</span></span></dt>
<dd><p>包含请求 URL。 是 <em>filename</em> 属性的别名。</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="urllib.error.HTTPError.code">
<span class="sig-name descname"><span class="pre">code</span></span></dt>
<dd><p>一个 HTTP 状态码，具体定义见 <span class="target" id="index-2"></span><a class="rfc reference external" href="https://datatracker.ietf.org/doc/html/rfc2616.html"><strong>RFC 2616</strong></a><span class="link-target"> [https://datatracker.ietf.org/doc/html/rfc2616.html]</span>。 这个数字的值对应于存放在 <a class="reference internal" href="http.server.xhtml#http.server.BaseHTTPRequestHandler.responses" title="http.server.BaseHTTPRequestHandler.responses"><code class="xref py py-attr docutils literal notranslate"><span class="pre">http.server.BaseHTTPRequestHandler.responses</span></code></a> 代码字典中的某个值。</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="urllib.error.HTTPError.reason">
<span class="sig-name descname"><span class="pre">reason</span></span></dt>
<dd><p>这通常是一个解释本次错误原因的字符串。 为 <em>msg</em> 属性的别名。</p>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="urllib.error.HTTPError.headers">
<span class="sig-name descname"><span class="pre">headers</span></span></dt>
<dd><p>导致 <a class="reference internal" href="#urllib.error.HTTPError" title="urllib.error.HTTPError"><code class="xref py py-exc docutils literal notranslate"><span class="pre">HTTPError</span></code></a> 的特定 HTTP 请求的 HTTP 响应头。 为 <em>hdrs</em> 属性的别名。</p>
<div class="versionadded">
<p><span class="versionmodified added">Added in version 3.4.</span></p>
</div>
</dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="urllib.error.HTTPError.fp">
<span class="sig-name descname"><span class="pre">fp</span></span></dt>
<dd><p>可供读取 HTTP 错误消息体的文件型对象。</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="urllib.error.ContentTooShortError">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">urllib.error.</span></span><span class="sig-name descname"><span class="pre">ContentTooShortError</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">msg</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">content</span></span></em><span class="sig-paren">)</span></dt>
<dd><p>此异常会在 <a class="reference internal" href="urllib.request.xhtml#urllib.request.urlretrieve" title="urllib.request.urlretrieve"><code class="xref py py-func docutils literal notranslate"><span class="pre">urlretrieve()</span></code></a> 函数检测到已下载的数据量少于预期量（由 <em>Content-Length</em> 标头给出）时被引发。</p>
<dl class="py attribute">
<dt class="sig sig-object py" id="urllib.error.ContentTooShortError.content">
<span class="sig-name descname"><span class="pre">content</span></span></dt>
<dd><p>已下载（并可能被截断）的数据。</p>
</dd></dl>

</dd></dl>

</section>


            <div class="clearer"></div>
          </div>
      </div>
      <div class="clearer"></div>
    </div>
  </body>
</html>